program SHE_ERP;
{$I C:\Sheild\Projetos\Delphi\Fontes\Lib\FastMM\FastMM4Options.inc} // incluir arquivo de configuração
{$SetPEFlags $20} // Permite que o aplicativo acesse até 4GB de RAM em sistemas x64

uses
  FastMM4,
  DSiWin32 in '..\..\..\..\Lib\Default\DSiWin32.pas',
  hkHints in '..\..\..\..\Lib\Default\HkHints.pas',
  StrInt in '..\..\..\..\Lib\Default\StrInt.pas',
  StrIntImp in '..\..\..\..\Lib\Default\StrIntImp.pas',
  Forms,
  SysUtils,
  uPrincipal in 'uPrincipal.pas' {FrmPrincipal},
  oPrincipal in '..\..\..\..\Lib\Default\oPrincipal.pas',
  bPrincipal in '..\..\..\..\Lib\Data Modulo\bPrincipal.pas' {FBird: TDataModule},
  pSplash in '..\..\..\..\Lib\Default\pSplash.pas' {FrmSplash},
  pSobre in '..\..\..\..\Lib\Default\pSobre.pas' {FrmSobre},
  pLogin in '..\..\..\..\Lib\Default\pLogin.pas' {FrmLogin},
  pSenha in '..\..\..\..\Lib\Default\pSenha.pas' {FrmSenha},
  pImpressoras in '..\..\..\..\Lib\Default\pImpressoras.pas' {FrmImpressoras},
  pEmConstrucao in '..\..\..\..\Lib\Default\pEmConstrucao.pas' {FrmEmConstrucao},
  pConsultaCNPJ in '..\..\..\..\Lib\Default\pConsultaCNPJ.pas' {FrmConsultaCNPJ},
  pDefault in '..\..\..\..\prj_2025\VER-OLD\pDefault.pas' {FrmDefault},
  pDefaultConsultaOld in '..\..\prj_2019\Default\pDefaultConsultaOld.pas' {FrmDefaultConsultaOld},
  pDefaultEdicao in '..\..\..\..\prj_2025\VER-OLD\pDefaultEdicao.pas' {FrmDefaultEdicao},
  pDefaultEdicaoGrid in '..\..\..\..\prj_2025\VER-OLD\pDefaultEdicaoGrid.pas' {FrmDefaultEdicaoGrid},
  pDefaultEditGrid in '..\..\..\..\prj_2025\VER-OLD\pDefaultEditGrid.pas' {FrmDefaultEditGrid},
  pDefaultConsultaGrid in '..\..\..\..\prj_2025\VER-OLD\pDefaultConsultaGrid.pas' {FrmDefaultConsultaGrid},
  pDefaultConsulta in '..\..\..\..\prj_2025\VER-OLD\pDefaultConsulta.pas' {FrmDefaultConsulta},
  pDefaultGrid in '..\..\..\..\prj_2025\VER-OLD\pDefaultGrid.pas' {FrmDefaultGrid},
  pcad_rep_edi in '..\padrao\pcad_rep_edi.pas' {frmcad_rep_edi},
  pcad_tra_edi in '..\padrao\pcad_tra_edi.pas' {frmcad_tra_edi},
  ptab_pag in '..\padrao\ptab_pag.pas' {frmtab_pag},
  pcad_for_edi in '..\padrao\pcad_for_edi.pas' {frmcad_for_edi},
  petiqueta_geral in '..\padrao\petiqueta_geral.pas' {FrmEtiqueta_Geral},
  ptab_nat in '..\padrao\ptab_nat.pas' {frmtab_nat},
  ptab_nat_edi in '..\padrao\ptab_nat_edi.pas' {frmtab_nat_edi},
  pven_prg in '..\padrao\pven_prg.pas' {frmven_prg},
  pctr_prg in '..\padrao\pctr_prg.pas' {frmctr_prg},
  pven_ped in '..\padrao\pven_ped.pas' {frmven_ped},
  pctr_ped_bai in '..\padrao\pctr_ped_bai.pas' {frmctr_ped_bai},
  pfin_dup_edi in '..\padrao\pfin_dup_edi.pas' {frmfin_dup_edi},
  pctr_ped in '..\padrao\pctr_ped.pas' {frmctr_ped},
  pcad_con in '..\padrao\pcad_con.pas' {frmcad_con},
  pcad_con_edi in '..\padrao\pcad_con_edi.pas' {frmcad_con_edi},
  pfin_rec_bai in '..\Padrao\pfin_rec_bai.pas' {frmfin_rec_bai},
  pfin_rec_con in '..\Padrao\pfin_rec_con.pas' {frmfin_rec_con},
  pRelatorios in '..\..\prj_2019\Relatorios\pRelatorios.pas' {FrmRelatorios},
  pPesquisa in '..\..\prj_2019\Default\pPesquisa.pas' {FrmPesquisa},
  pCFeSat in '..\Padrao\pCFeSat.pas' {FrmCFeSat},
  pNFeSaida in '..\..\prj_2019\NFe\pNFeSaida.pas' {FrmNFeSaida},
  pCAD_TRA in '..\..\prj_2019\Default\pCAD_TRA.pas' {FrmCAD_TRA},
  pNFeSaidaConsulta in '..\..\prj_2019\NFe\pNFeSaidaConsulta.pas' {FrmNFeSaidaConsulta},
  pCAD_REP in '..\..\prj_2019\Default\pCAD_REP.pas' {FrmCAD_REP},
  pcad_cli in '..\Padrao\pcad_cli.pas' {frmcad_cli},
  pcad_for in '..\Padrao\pcad_for.pas' {frmcad_for},
  qProduto_Custo_Importado in '..\..\prj_2019\Relatorios\qProduto_Custo_Importado.pas' {qrpProduto_Custo_Importado: TQuickRep},
  pProduto_Pesquisa in '..\..\prj_2019\Produtos\pProduto_Pesquisa.pas' {FrmProduto_Pesquisa},
  pProduto_Grupo in '..\..\prj_2019\Produtos\pProduto_Grupo.pas' {FrmProduto_Grupo},
  pProduto_SubGrupo in '..\..\prj_2019\Produtos\pProduto_SubGrupo.pas' {FrmProduto_SubGrupo},
  pProduto_Categoria in '..\..\prj_2019\Produtos\pProduto_Categoria.pas' {FrmProduto_Categoria},
  qProduto_Estoque in '..\..\prj_2019\Relatorios\qProduto_Estoque.pas' {qrpProduto_Estoque: TQuickRep},
  qProduto_Estoque_Etiqueta in '..\..\prj_2019\Relatorios\qProduto_Estoque_Etiqueta.pas' {qrpProduto_Estoque_Etiqueta: TQuickRep},
  qProduto_Compra_Planejamento in '..\..\prj_2019\Relatorios\qProduto_Compra_Planejamento.pas' {qrpProduto_Compra_Planejamento: TQuickRep},
  qGerencial_Estoque_Unidade_Medida in '..\..\prj_2019\Relatorios\qGerencial_Estoque_Unidade_Medida.pas' {qrpGerencial_Estoque_Unidade_Medida: TQuickRep},
  qGerencial_NF_Peso in '..\..\prj_2019\Relatorios\qGerencial_NF_Peso.pas' {qrpGerencial_NF_Peso: TQuickRep},
  pProduto_Instrucao_Lavagem in '..\..\prj_2019\Produtos\pProduto_Instrucao_Lavagem.pas' {FrmProduto_Instrucao_Lavagem},
  pcad_cli_edi in '..\Padrao\pcad_cli_edi.pas' {frmcad_cli_edi},
  pProduto_Cor in '..\..\prj_2019\Produtos\pProduto_Cor.pas' {FrmProduto_Cor},
  pProduto_Custo_Importado in '..\..\prj_2019\Custos\pProduto_Custo_Importado.pas' {FrmProduto_Custo_Importado},
  pProduto_Custo_Importado_Edicao in '..\..\prj_2019\Custos\pProduto_Custo_Importado_Edicao.pas' {FrmProduto_Custo_Importado_Edicao},
  pExporta in '..\..\prj_2019\Default\pExporta.pas' {FrmExporta},
  pAviso_Reserva in '..\..\prj_2019\Pedidos\pAviso_Reserva.pas' {FrmAviso_Reserva},
  pProduto_Devolucao_Cancelamento in '..\..\prj_2019\Pedidos\pProduto_Devolucao_Cancelamento.pas' {FrmProduto_Devolucao_Cancelamento},
  pProduto_Imagem in '..\..\prj_2019\Produtos\pProduto_Imagem.pas' {FrmProduto_Imagem},
  qcob_ped_oca in '..\Relatorios\qcob_ped_oca.pas' {qrpcob_ped_oca: TQuickRep},
  qcob_rom in '..\Relatorios\qcob_rom.pas' {qrpcob_rom: TQuickRep},
  qcob_rom_ref in '..\Relatorios\qcob_rom_ref.pas' {qrpcob_rom_ref: TQuickRep},
  qfin_dup in '..\Relatorios\qfin_dup.pas' {qrpfin_dup: TQuickRep},
  qfin_rec_ger in '..\Relatorios\qfin_rec_ger.pas' {qrpfin_rec_ger: TQuickRep},
  qfin_rec_ger_consolidado in '..\Relatorios\qfin_rec_ger_consolidado.pas' {qrpfin_rec_ger_consolidado: TQuickRep},
  qpag_com in '..\Relatorios\qpag_com.pas' {qrppag_com: TQuickRep},
  qrom_con_001 in '..\Relatorios\qrom_con_001.pas' {qrprom_con_001: TQuickRep},
  qven_prc in '..\Relatorios\qven_prc.pas' {qrpven_prc: TQuickRep},
  qPCConferencia in '..\..\prj_2019\Relatorios\qPCConferencia.pas' {qrpPCConferencia: TQuickRep},
  qPCOrdem in '..\..\prj_2019\Relatorios\qPCOrdem.pas' {qrpPCOrdem: TQuickRep},
  parquivo_geral in '..\Padrao\parquivo_geral.pas' {frmarquivo_geral},
  pfin_dup in '..\Padrao\pfin_dup.pas' {frmfin_dup},
  qven_con in '..\Relatorios\qven_con.pas' {qrpven_con: TQuickRep},
  ppag_com in '..\Padrao\ppag_com.pas' {frmpag_com},
  qven_prg in '..\Relatorios\qven_prg.pas' {qrpven_prg: TQuickRep},
  qEtiqueta_Cartela in '..\..\prj_2019\Etiquetas\qEtiqueta_Cartela.pas' {qrpEtiqueta_Cartela: TQuickRep},
  qEtiqueta_Cartela2 in '..\..\prj_2019\Etiquetas\qEtiqueta_Cartela2.pas' {qrpEtiqueta_Cartela2: TQuickRep},
  qEtiqueta_Id in '..\..\prj_2019\Etiquetas\qEtiqueta_Id.pas' {qrpEtiqueta_Id: TQuickRep},
  qPROSpedFiscal in '..\..\prj_2019\Relatorios\qPROSpedFiscal.pas' {qrpPROSpedFiscal: TQuickRep},
  pProduto_SubCategoria in '..\..\prj_2019\Produtos\pProduto_SubCategoria.pas' {FrmProduto_SubCategoria},
  pProduto_Preco_Faixa_Comissao in '..\..\prj_2019\Produtos\pProduto_Preco_Faixa_Comissao.pas' {FrmProduto_Preco_Faixa_Comissao},
  pFRecebimento_Edicao in '..\..\prj_2019\Financeiro\pFRecebimento_Edicao.pas' {FrmFRecebimento_Edicao},
  pPesquisaCodigoMunicipal in '..\..\prj_2019\Default\pPesquisaCodigoMunicipal.pas' {FrmPesquisaCodigoMunicipal},
  pPesquisaLogradouros in '..\..\prj_2019\Default\pPesquisaLogradouros.pas' {FrmPesquisaLogradouros},
  pEstoqueDefeitos in '..\..\prj_2019\Estoque\pEstoqueDefeitos.pas' {FrmEstoqueDefeitos},
  qven_ped in '..\Relatorios\qven_ped.pas' {qrpven_ped: TQuickRep},
  qcob_ped in '..\Relatorios\qcob_ped.pas' {qrpcob_ped: TQuickRep},
  qsep_ped in '..\Relatorios\qsep_ped.pas' {qrpsep_ped: TQuickRep},
  pProdutos in '..\..\prj_2024\Produtos\pProdutos.pas' {FrmProdutos},
  pProduto in '..\..\prj_2019\Produtos\pProduto.pas' {FrmProduto},
  qFicha_Tecnica in '..\..\prj_2024\Relatórios\Produtos\qFicha_Tecnica.pas' {qrpFicha_Tecnica: TQuickRep},
  qGER_CRD in '..\..\..\..\prj_2025\VER-OLD\QGER_CRD.pas' {QRPGER_CRD: TQuickRep},
  pent_pro in '..\..\..\..\prj_2025\VER-OLD\pent_pro.pas' {frment_pro},
  pven_nfd in '..\..\..\..\prj_2025\VER-OLD\pven_nfd.pas' {frmven_nfd},
  pven_nfe in '..\..\..\..\prj_2025\VER-OLD\pven_nfe.pas' {frmven_nfe},
  peti_pro in '..\Padrao\peti_pro.pas' {frmeti_pro},
  pSHE_DEF_EDI in '..\..\..\..\prj_2025\VER-OLD\pSHE_DEF_EDI.pas' {FrmSHE_DEF_EDI},
  pSHE_DEF_PSQ in '..\..\..\..\prj_2025\VER-OLD\pSHE_DEF_PSQ.pas' {FrmSHE_DEF_PSQ},
  pCAD_PRO_PSQ in '..\..\..\..\prj_2025\VER-OLD\pCAD_PRO_PSQ.pas' {FrmCAD_PRO_PSQ},
  pPadr3 in '..\..\..\..\prj_2025\VER-OLD\pPadr3.pas' {FrmPadr3},
  pCAD_PRO_EDI in '..\..\..\..\prj_2025\VER-OLD\pCAD_PRO_EDI.pas' {FrmCAD_PRO_EDI},
  pcad_cli_inf in '..\..\..\..\prj_2025\VER-OLD\pcad_cli_inf.pas' {frmcad_cli_inf},
  pcai_abr in '..\..\..\..\prj_2025\VER-OLD\pcai_abr.pas' {frmcai_abr},
  pcai_fec in '..\..\..\..\prj_2025\VER-OLD\pcai_fec.pas' {frmcai_fec},
  pcai_mov in '..\..\..\..\prj_2025\VER-OLD\pcai_mov.pas' {frmcai_mov},
  pcai_sar in '..\..\..\..\prj_2025\VER-OLD\pcai_sar.pas' {frmcai_sar},
  pcai_sar_edi in '..\..\..\..\prj_2025\VER-OLD\pcai_sar_edi.pas' {frmcai_sar_edi},
  pEXP_SEP_COL in '..\..\..\..\prj_2025\VER-OLD\pEXP_SEP_COL.pas' {FrmEXP_SEP_COL},
  pEXP_SEP_MAN in '..\..\..\..\prj_2025\VER-OLD\pEXP_SEP_MAN.pas' {FrmEXP_SEP_MAN},
  pimporta_geral in '..\..\..\..\prj_2025\VER-OLD\pimporta_geral.pas' {frmimporta_geral},
  pimporta_geral_favorecido in '..\..\..\..\prj_2025\VER-OLD\pimporta_geral_favorecido.pas' {frmimporta_geral_favorecido},
  pnfe_cce in '..\..\..\..\prj_2025\VER-OLD\pnfe_cce.pas' {frmnfe_cce},
  pNFeConsulta in '..\..\..\..\prj_2025\VER-OLD\pNFeConsulta.pas' {FrmNFeConsulta},
  pNFeConsultaSefaz in '..\..\..\..\prj_2025\VER-OLD\pNFeConsultaSefaz.pas' {FrmNFeConsultaSefaz},
  pemail in '..\..\..\..\prj_2025\VER-OLD\pemail.pas' {FrmEmail},
  pPadr1 in '..\..\..\..\prj_2025\VER-OLD\ppadr1.pas' {FrmPadr1},
  pctr_nfe in '..\..\..\..\prj_2025\VER-OLD\pctr_nfe.pas' {frmctr_nfe},
  pPadr2 in '..\..\..\..\prj_2025\VER-OLD\pPadr2.pas' {FrmPadr2},
  ppesquisa_geral in '..\..\..\..\prj_2025\VER-OLD\ppesquisa_geral.pas' {FrmPesquisa_Geral},
  prelatorio_geral in '..\Padrao\prelatorio_geral.pas' {frmrelatorio_geral},
  pConsulta in '..\..\..\..\prj_2025\VER-OLD\pConsulta.pas' {FrmConsulta},
  pEstoque in '..\..\..\..\prj_2025\VER-OLD\pEstoque.pas' {FrmEstoque},
  pCAD_PRO_EST_DEL in '..\..\..\..\prj_2025\VER-OLD\pCAD_PRO_EST_DEL.pas' {FrmCAD_PRO_EST_DEL},
  pven_rom in '..\..\..\..\prj_2025\VER-OLD\pven_rom.pas' {frmven_rom},
  pctr_rom in '..\..\..\..\prj_2025\VER-OLD\pctr_rom.pas' {frmctr_rom},
  qEST_ENT_ROM in '..\..\..\..\Lib\Relatórios\Estoque\qEST_ENT_ROM.pas' {qrpEST_ENT_ROM: TQuickRep},
  qEST_ETQ_PAD in '..\..\..\..\Lib\Relatórios\Estoque\qEST_ETQ_PAD.pas' {qrpEST_ETQ_PAD: TQuickRep},
  qEST_ETQ_PEQ in '..\..\..\..\Lib\Relatórios\Estoque\qEST_ETQ_PEQ.pas' {qrpEST_ETQ_PEQ: TQuickRep},
  pSegmentos in '..\..\Lib\Tabelas\pSegmentos.pas' {FrmSegmentos},
  pPSQCAD in '..\..\..\..\prj_2025\VER-OLD\pPSQCAD.pas' {FrmPSQCAD},
  pPSQEND in '..\..\..\..\prj_2025\VER-OLD\pPSQEND.pas' {FrmPSQEND},
  pven_prc in '..\..\..\..\prj_2025\VER-OLD\pven_prc.pas' {frmven_prc},
  pctr_prc in '..\..\..\..\prj_2025\VER-OLD\pctr_prc.pas' {frmctr_prc};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'SHE ERP';
  FrmSplash := TFrmSplash.Create(Nil);
  FrmSplash.Refresh;
  FrmSplash.Show;

  FBird := TFBird.Create(Application);

  FrmLogin := TFrmLogin.Create(Nil);
  FrmLogin.Refresh;
  FrmLogin.ShowModal;

  Application.CreateForm(TFrmPrincipal, FrmPrincipal);
  Application.Initialize;

  FreeAndNil(FrmSplash);
  FreeAndNil(FrmLogin);

  Application.Run;
  FreeAndNil(FrmPrincipal);
end.
