program SHE_ERP;
{$I C:\Sheild\Projetos\Delphi\Fontes\Lib\FastMM\FastMM4Options.inc} // incluir arquivo de configuração
{$SetPEFlags $20} // Permite que o aplicativo acesse até 4GB de RAM em sistemas x64

uses
  FastMM4 in '..\..\..\Lib\FastMM\FastMM4.pas',
  Forms,
  SysUtils,
  oIBXRetryTransaction in '..\..\..\Lib\Default\oIBXRetryTransaction.pas',
  DelphiZXingQRCode in '..\..\..\Lib\Default\DelphiZXIngQRCode.pas',
  hkHints in '..\..\..\Lib\Default\HkHints.pas',
  StrInt in '..\..\..\Lib\Default\StrInt.pas',
  StrIntImp in '..\..\..\Lib\Default\StrIntImp.pas',
  pSplash in '..\..\..\Lib\Default\pSplash.pas' {FrmSplash},
  pSobre in '..\..\..\Lib\Default\pSobre.pas' {FrmSobre},
  pLogin in '..\..\..\Lib\Default\pLogin.pas' {FrmLogin},
  pSenha in '..\..\..\Lib\Default\pSenha.pas' {FrmSenha},
  pConstrucao in '..\..\..\Lib\Default\pConstrucao.pas' {FrmConstrucao},
  pImpressoras in '..\..\..\Lib\Relatórios\pImpressoras.pas' {FrmImpressoras},
  oPrincipal in '..\..\..\Lib\Default\oPrincipal.pas',
  bPrincipal in '..\..\..\Lib\Data Modulo\bPrincipal.pas' {FBird: TDataModule},
  uPrincipal in 'uPrincipal.pas' {FrmPrincipal},
  pSHE_DEF_EDI in '..\..\..\Lib\Default\pSHE_DEF_EDI.pas' {FrmSHE_DEF_EDI},
  pSHE_DEF_PSQ in '..\..\..\Lib\Default\pSHE_DEF_PSQ.pas' {FrmSHE_DEF_PSQ},
  pDefault in '..\..\Padrao\Default\pDefault.pas' {FrmDefault},
  pDefaultConsulta in '..\..\Padrao\Default\pDefaultConsulta.pas' {FrmDefaultConsulta},
  pDefaultConsultaGrid in '..\..\Padrao\Default\pDefaultConsultaGrid.pas' {FrmDefaultConsultaGrid},
  pDefaultConsultaOld in '..\..\Padrao\Default\pDefaultConsultaOld.pas' {FrmDefaultConsultaOld},
  pDefaultEdicao in '..\..\Padrao\Default\pDefaultEdicao.pas' {FrmDefaultEdicao},
  pDefaultEdicaoGrid in '..\..\Padrao\Default\pDefaultEdicaoGrid.pas' {FrmDefaultEdicaoGrid},
  pDefaultGrid in '..\..\Padrao\Default\pDefaultGrid.pas' {FrmDefaultGrid},
  pPadr1 in '..\..\Padrao\ppadr1.pas' {FrmPadr1},
  pPadr2 in '..\..\Padrao\pPadr2.pas' {FrmPadr2},
  pPadr3 in '..\..\Padrao\pPadr3.pas' {FrmPadr3},
  pPadr5 in '..\..\Padrao\pPadr5.pas' {FrmPadr5},
  pConsulta in '..\..\Padrao\Default\pConsulta.pas' {FrmConsulta},
  pRelatorios in '..\..\..\Lib\Relatórios\pRelatorios.pas' {FrmRelatorios},
  pPesquisa in '..\..\Padrao\Consultas\pPesquisa.pas' {FrmPesquisa},
  pCAD_PRO_EDI in '..\..\Padrao\Produtos\pcad_pro_edi.pas' {FrmCAD_PRO_EDI},
  pProduto in '..\..\Padrao\Produtos\pProduto.pas' {FrmProduto},
  pExporta in '..\..\..\Lib\Relatórios\pExporta.pas' {FrmExporta},
  pProduto_Instrucao_Lavagem in '..\..\Padrao\Produtos\pProduto_Instrucao_Lavagem.pas' {FrmProduto_Instrucao_Lavagem},
  pRelatorios_OLD in '..\..\Padrao\Relatorios\pRelatorios_OLD.pas' {FrmRelatorios_OLD},
  qProduto_Compra_Planejamento in '..\..\Padrao\Relatorios\qProduto_Compra_Planejamento.pas' {qrpProduto_Compra_Planejamento: TQuickRep},
  qProduto_Custo_Importado in '..\..\Padrao\Relatorios\qProduto_Custo_Importado.pas' {qrpProduto_Custo_Importado: TQuickRep},
  qProduto_Estoque in '..\..\Padrao\Relatorios\qProduto_Estoque.pas' {qrpProduto_Estoque: TQuickRep},
  qProduto_Estoque_Etiqueta in '..\..\Padrao\Relatorios\qProduto_Estoque_Etiqueta.pas' {qrpProduto_Estoque_Etiqueta: TQuickRep},
  pcad_cli_inf in '..\..\Padrao\Cadastros\pcad_cli_inf.pas' {frmcad_cli_inf},
  pcad_con in '..\..\Padrao\Cadastros\pcad_con.pas' {frmcad_con},
  pcad_con_edi in '..\..\Padrao\Cadastros\pcad_con_edi.pas' {frmcad_con_edi},
  pPesquisaCodigoMunicipal in '..\..\Padrao\Consultas\pPesquisaCodigoMunicipal.pas' {FrmPesquisaCodigoMunicipal},
  pPesquisaLogradouros in '..\..\Padrao\Consultas\pPesquisaLogradouros.pas' {FrmPesquisaLogradouros},
  pPSQCAD in '..\..\Padrao\Consultas\pPSQCAD.pas' {FrmPSQCAD},
  pPSQEND in '..\..\Padrao\Consultas\pPSQEND.pas' {FrmPSQEND},
  pPSQ_CAD_PAD in '..\..\Padrao\Consultas\pPSQ_CAD_PAD.pas' {FrmPSQ_CAD_PAD},
  pemail in '..\..\Padrao\pemail.pas' {FrmEmail},
  pimporta_geral in '..\..\Padrao\pimporta_geral.pas' {frmimporta_geral},
  pimporta_geral_favorecido in '..\..\Padrao\pimporta_geral_favorecido.pas' {frmimporta_geral_favorecido},
  pNFeConsultaSefaz in '..\..\..\Lib\Sefaz\pNFeConsultaSefaz.pas' {FrmNFeConsultaSefaz},
  pven_nfe in '..\..\..\Lib\Fiscal\pven_nfe.pas' {FrmVEN_NFE},
  parquivo_geral in '..\..\Padrao\Relatorios\parquivo_geral.pas' {frmarquivo_geral},
  prelatorio_geral in '..\..\Padrao\Relatorios\prelatorio_geral.pas' {frmrelatorio_geral},
  qcob_ped in '..\..\Padrao\Relatorios\qcob_ped.pas' {qrpcob_ped: TQuickRep},
  qcob_ped_oca in '..\..\Padrao\Relatorios\qcob_ped_oca.pas' {qrpcob_ped_oca: TQuickRep},
  qcob_rom in '..\..\Padrao\Relatorios\qcob_rom.pas' {qrpcob_rom: TQuickRep},
  qcob_rom_ref in '..\..\Padrao\Relatorios\qcob_rom_ref.pas' {qrpcob_rom_ref: TQuickRep},
  qpag_com in '..\..\Padrao\Relatorios\qpag_com.pas' {qrppag_com: TQuickRep},
  qPCConferencia in '..\..\Padrao\Relatorios\qPCConferencia.pas' {qrpPCConferencia: TQuickRep},
  qPCOrdem in '..\..\Padrao\Relatorios\qPCOrdem.pas' {qrpPCOrdem: TQuickRep},
  qrom_con_001 in '..\..\Padrao\Relatorios\qrom_con_001.pas' {qrprom_con_001: TQuickRep},
  qsep_ped in '..\..\Padrao\Relatorios\qsep_ped.pas' {qrpsep_ped: TQuickRep},
  qven_con in '..\..\Padrao\Relatorios\qven_con.pas' {qrpven_con: TQuickRep},
  qven_ped in '..\..\Padrao\Relatorios\qven_ped.pas' {qrpven_ped: TQuickRep},
  qven_prc in '..\..\Padrao\Relatorios\qven_prc.pas' {qrpven_prc: TQuickRep},
  pven_nfd in '..\..\Padrao\Fiscal\pven_nfd.pas' {frmven_nfd},
  pctr_ped in '..\..\Padrao\Vendas\pctr_ped.pas' {frmctr_ped},
  pctr_ped_bai in '..\..\Padrao\Vendas\pctr_ped_bai.pas' {frmctr_ped_bai},
  pctr_rom in '..\..\Padrao\Vendas\pctr_rom.pas' {frmctr_rom},
  pven_ped in '..\..\Padrao\Vendas\pven_ped.pas' {FrmVEN_PED},
  pven_rom in '..\..\Padrao\Vendas\pven_rom.pas' {frmven_rom},
  qfin_dup in '..\..\Padrao\Relatorios\qfin_dup.pas' {qrpfin_dup: TQuickRep},
  pnfe_cce in '..\..\Padrao\Fiscal\pnfe_cce.pas' {frmnfe_cce},
  pfin_dup in '..\..\Padrao\Financeiro\pfin_dup.pas' {frmfin_dup},
  pfin_dup_edi in '..\..\Padrao\Financeiro\pfin_dup_edi.pas' {frmfin_dup_edi},
  pfin_rec_bai in '..\..\Padrao\Financeiro\pfin_rec_bai.pas' {frmfin_rec_bai},
  pfin_rec_con in '..\..\Padrao\Financeiro\pfin_rec_con.pas' {frmfin_rec_con},
  pFRecebimento_Edicao in '..\..\Padrao\Financeiro\pFRecebimento_Edicao.pas' {FrmFRecebimento_Edicao},
  qfin_rec_ger in '..\..\Padrao\Relatorios\qfin_rec_ger.pas' {qrpfin_rec_ger: TQuickRep},
  qfin_rec_ger_consolidado in '..\..\Padrao\Relatorios\qfin_rec_ger_consolidado.pas' {qrpfin_rec_ger_consolidado: TQuickRep},
  pProduto_Categoria in '..\..\Padrao\Produtos\pProduto_Categoria.pas' {FrmProduto_Categoria},
  pProduto_Cor in '..\..\Padrao\Produtos\pProduto_Cor.pas' {FrmProduto_Cor},
  pProduto_Devolucao_Cancelamento in '..\..\Padrao\Produtos\pProduto_Devolucao_Cancelamento.pas' {FrmProduto_Devolucao_Cancelamento},
  pProduto_Grupo in '..\..\Padrao\Produtos\pProduto_Grupo.pas' {FrmProduto_Grupo},
  pProduto_Imagem in '..\..\Padrao\Produtos\pProduto_Imagem.pas' {FrmProduto_Imagem},
  pProduto_Preco_Faixa_Comissao in '..\..\Padrao\Produtos\pProduto_Preco_Faixa_Comissao.pas' {FrmProduto_Preco_Faixa_Comissao},
  pProduto_SubCategoria in '..\..\Padrao\Produtos\pProduto_SubCategoria.pas' {FrmProduto_SubCategoria},
  pProduto_SubGrupo in '..\..\Padrao\Produtos\pProduto_SubGrupo.pas' {FrmProduto_SubGrupo},
  pProduto_Pesquisa in '..\..\Padrao\Consultas\pProduto_Pesquisa.pas' {FrmProduto_Pesquisa},
  pConsultaCNPJ in '..\..\Padrao\Consultas\pConsultaCNPJ.pas' {FrmConsultaCNPJ},
  pcai_abr in '..\..\Padrao\Caixa\pcai_abr.pas' {frmcai_abr},
  pcai_fec in '..\..\Padrao\Caixa\pcai_fec.pas' {frmcai_fec},
  pcai_mov in '..\..\Padrao\Caixa\pcai_mov.pas' {frmcai_mov},
  pcai_sar in '..\..\Padrao\Caixa\pcai_sar.pas' {frmcai_sar},
  pcai_sar_edi in '..\..\Padrao\Caixa\pcai_sar_edi.pas' {frmcai_sar_edi},
  pNFeConsulta in '..\..\Padrao\Fiscal\pNFeConsulta.pas' {FrmNFeConsulta},
  pNFeSaida in '..\..\Padrao\Fiscal\pNFeSaida.pas' {FrmNFeSaida},
  pNFeSaidaConsulta in '..\..\Padrao\Fiscal\pNFeSaidaConsulta.pas' {FrmNFeSaidaConsulta},
  pEtiqueta_Geral in '..\..\Padrao\Etiquetas\petiqueta_geral.pas' {FrmEtiqueta_Geral},
  qEtiqueta_Cartela in '..\..\Padrao\Relatorios\Etiquetas\qEtiqueta_Cartela.pas' {qrpEtiqueta_Cartela: TQuickRep},
  qEtiqueta_Cartela2 in '..\..\Padrao\Relatorios\Etiquetas\qEtiqueta_Cartela2.pas' {qrpEtiqueta_Cartela2: TQuickRep},
  qEtiqueta_Id in '..\..\Padrao\Relatorios\Etiquetas\qEtiqueta_Id.pas' {qrpEtiqueta_Id: TQuickRep},
  pent_pro in '..\..\Padrao\Estoque\pent_pro.pas' {frment_pro},
  pEstoque in '..\..\Padrao\Estoque\pEstoque.pas' {FrmEstoque},
  pEstoqueDefeitos in '..\..\Padrao\Estoque\pEstoqueDefeitos.pas' {FrmEstoqueDefeitos},
  peti_pro in '..\..\Padrao\Estoque\peti_pro.pas' {frmeti_pro},
  pEXP_SEP_COL in '..\..\Padrao\Expedição\pEXP_SEP_COL.pas' {FrmEXP_SEP_COL},
  pEXP_SEP_MAN in '..\..\Padrao\Expedição\pEXP_SEP_MAN.pas' {FrmEXP_SEP_MAN},
  pctr_prc in '..\..\Padrao\Compras\pctr_prc.pas' {frmctr_prc},
  pven_prc in '..\..\Padrao\Compras\pven_prc.pas' {frmven_prc},
  pctr_prg in '..\..\Padrao\Programados\pctr_prg.pas' {frmctr_prg},
  pven_prg in '..\..\Padrao\Programados\pven_prg.pas' {frmven_prg},
  ptab_nat in '..\..\Padrao\Tabelas\ptab_nat.pas' {frmtab_nat},
  ptab_nat_edi in '..\..\Padrao\Tabelas\ptab_nat_edi.pas' {frmtab_nat_edi},
  ptab_pag in '..\..\Padrao\Tabelas\ptab_pag.pas' {frmtab_pag},
  ppag_com in '..\..\Padrao\Financeiro\ppag_com.pas' {frmpag_com},
  pProduto_Custo_Importado in '..\..\Padrao\Custos\pProduto_Custo_Importado.pas' {FrmProduto_Custo_Importado},
  pProduto_Custo_Importado_Edicao in '..\..\Padrao\Custos\pProduto_Custo_Importado_Edicao.pas' {FrmProduto_Custo_Importado_Edicao},
  pProduto_Segmento in '..\..\Padrao\Produtos\pProduto_Segmento.pas' {FrmProduto_Segmento},
  qEST_ENT_ROM in '..\..\..\Lib\Relatórios\Estoque\qEST_ENT_ROM.pas' {qrpEST_ENT_ROM: TQuickRep},
  qEST_ETQ_PAD in '..\..\..\Lib\Relatórios\Estoque\qEST_ETQ_PAD.pas' {qrpEST_ETQ_PAD: TQuickRep},
  qEST_ETQ_PEQ in '..\..\..\Lib\Relatórios\Estoque\qEST_ETQ_PEQ.pas' {qrpEST_ETQ_PEQ: TQuickRep},
  pCAD_PRO_PSQ in '..\..\..\Lib\Produtos\pCAD_PRO_PSQ.pas' {FrmCAD_PRO_PSQ},
  pctr_nfe in '..\..\..\Lib\Fiscal\pctr_nfe.pas' {frmctr_nfe},
  pcad_cli_edi in '..\..\Padrao\Cadastros\pcad_cli_edi.pas' {frmcad_cli_edi},
  pcad_cli in '..\..\Padrao\Cadastros\pcad_cli.pas' {frmcad_cli},
  pcad_for in '..\..\Padrao\Cadastros\pcad_for.pas' {frmcad_for},
  pcad_for_edi in '..\..\Padrao\Cadastros\pcad_for_edi.pas' {frmcad_for_edi},
  pcad_rep in '..\..\Padrao\Cadastros\pCAD_REP.pas' {frmcad_rep},
  pcad_rep_edi in '..\..\Padrao\Cadastros\pcad_rep_edi.pas' {frmcad_rep_edi},
  pcad_tra in '..\..\Padrao\Cadastros\pCAD_TRA.pas' {frmcad_tra},
  pcad_tra_edi in '..\..\Padrao\Cadastros\pcad_tra_edi.pas' {frmcad_tra_edi},
  pCAD_PRO_EST_DEL in '..\..\Padrao\Estoque\pCAD_PRO_EST_DEL.pas' {FrmCAD_PRO_EST_DEL},
  qven_prg in '..\..\Padrao\Relatorios\qven_prg.pas' {qrpven_prg: TQuickRep},
  qger_prg_pro_ger in '..\..\Padrao\Relatorios\qger_prg_pro_ger.pas' {qrpger_prg_pro_ger: TQuickRep},
  pAviso_Reserva in '..\..\Padrao\Vendas\pAviso_Reserva.pas' {FrmAviso_Reserva},
  qFicha_Tecnica in '..\..\..\Lib\Relatórios\Produtos\qFicha_Tecnica.pas' {qrpFicha_Tecnica: TQuickRep},
  QGER_FIS_CFOP in '..\..\..\Lib\Relatórios\Gerenciais\Fiscal\QGER_FIS_CFOP.pas' {QRPGER_FIS_CFOP: TQuickRep},
  QGER_PDV_CRD in '..\..\..\Lib\Relatórios\Gerenciais\Vendas\QGER_PDV_CRD.pas' {QRPGER_PDV_CRD: TQuickRep},
  qGER_EST_PRO in '..\..\..\Lib\Relatórios\Gerenciais\Estoque\QGER_EST_PRO.pas' {QRPGER_EST_PRO: TQuickRep},
  QGER_EST_INV in '..\..\..\Lib\Relatórios\Gerenciais\Estoque\QGER_EST_INV.pas' {QRPGER_EST_INV: TQuickRep},
  pPesquisa_OLD in '..\..\Padrao\Consultas\pPesquisa_OLD.pas' {FrmPesquisa_OLD},
  QGER_FIS_PESO in '..\..\..\Lib\Relatórios\Gerenciais\Fiscal\QGER_FIS_PESO.pas' {QRPGER_FIS_PESO: TQuickRep};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'SHE-ERP';

  FrmSplash := TFrmSplash.Create(Nil);
  FrmSplash.Refresh;
  FrmSplash.Show;

  FBird := TFBird.Create(Application);

  FrmLogin := TFrmLogin.Create(Nil);
  FrmLogin.ShowModal;

  Application.CreateForm(TFrmPrincipal, FrmPrincipal);
  Application.Initialize;

  FreeAndNil(FrmSplash);
  FreeAndNil(FrmLogin);

  oPRN_EXE(Application.Handle,'Relatórios');
  
  Application.Run;
  FreeAndNil(FrmPrincipal);
end.
