program SHE_ERP;
{$I C:\Sheild\Projetos\Delphi\Fontes\Lib\FastMM\FastMM4Options.inc} // incluir arquivo de configuração
{$SetPEFlags $20} // Permite que o aplicativo acesse até 4GB de RAM em sistemas x64

uses
  FastMM4,
  DSiWin32 in '..\Lib\Default\DSiWin32.pas',
  hkHints in '..\Lib\Default\HkHints.pas',
  StrInt in '..\Lib\Default\StrInt.pas',
  StrIntImp in '..\Lib\Default\StrIntImp.pas',
  Forms,
  SysUtils,
  uPrincipal in 'uPrincipal.pas' {FrmPrincipal},
  oPrincipal in '..\Lib\Default\oPrincipal.pas',
  bPrincipal in '..\Lib\Data Modulo\bPrincipal.pas' {FBird: TDataModule},
  pSplash in '..\Lib\Default\pSplash.pas' {FrmSplash},
  pSobre in '..\Lib\Default\pSobre.pas' {FrmSobre},
  pLogin in '..\Lib\Default\pLogin.pas' {FrmLogin},
  pSenha in '..\Lib\Default\pSenha.pas' {FrmSenha},
  pImpressoras in '..\Lib\Default\pImpressoras.pas' {FrmImpressoras},
  pConsultaCNPJ in '..\Lib\Default\pConsultaCNPJ.pas' {FrmConsultaCNPJ},
  pSHE_DEF_PSQ in '..\Lib\Default\pSHE_DEF_PSQ.pas' {FrmSHE_DEF_PSQ},
  pPSQ_CAD_PAD in '..\Lib\Pesquisas\pPSQ_CAD_PAD.pas' {FrmPSQ_CAD_PAD},
  pPadr1 in '..\SHE-OLD\Padrao\ppadr1.pas' {FrmPadr1},
  pPadr2 in '..\SHE-OLD\Padrao\pPadr2.pas' {FrmPadr2},
  pPadr3 in '..\SHE-OLD\Padrao\pPadr3.pas' {FrmPadr3},
  pConsulta in '..\SHE-OLD\Padrao\pConsulta.pas' {FrmConsulta},
  pDefaultConsultaOld in '..\SHE-OLD\Padrao\pDefaultConsultaOld.pas' {FrmDefaultConsultaOld},
  pDefault in '..\SHE-OLD\Padrao\pDefault.pas' {FrmDefault},
  pDefaultEdicao in '..\SHE-OLD\Padrao\pDefaultEdicao.pas' {FrmDefaultEdicao},
  pDefaultEdicaoGrid in '..\SHE-OLD\Padrao\pDefaultEdicaoGrid.pas' {FrmDefaultEdicaoGrid},
  pDefaultEditGrid in '..\SHE-OLD\Padrao\pDefaultEditGrid.pas' {FrmDefaultEditGrid},
  pDefaultConsultaGrid in '..\SHE-OLD\Padrao\pDefaultConsultaGrid.pas' {FrmDefaultConsultaGrid},
  pDefaultConsulta in '..\SHE-OLD\Padrao\pDefaultConsulta.pas' {FrmDefaultConsulta},
  pDefaultGrid in '..\SHE-OLD\Padrao\pDefaultGrid.pas' {FrmDefaultGrid},
  pPesquisa in '..\SHE-OLD\Padrao\pPesquisa.pas' {FrmPesquisa},
  ppesquisa_geral in '..\SHE-OLD\Padrao\ppesquisa_geral.pas' {FrmPesquisa_Geral},
  pSegmentos in '..\SHE-OLD\Padrao\pSegmentos.pas' {FrmSegmentos},
  pcad_rep_edi in '..\SHE-OLD\padrao\pcad_rep_edi.pas' {frmcad_rep_edi},
  pcad_tra_edi in '..\SHE-OLD\padrao\pcad_tra_edi.pas' {frmcad_tra_edi},
  ptab_pag in '..\SHE-OLD\padrao\ptab_pag.pas' {frmtab_pag},
  pcad_for_edi in '..\SHE-OLD\padrao\pcad_for_edi.pas' {frmcad_for_edi},
  petiqueta_geral in '..\SHE-OLD\padrao\petiqueta_geral.pas' {FrmEtiqueta_Geral},
  ptab_nat in '..\SHE-OLD\padrao\ptab_nat.pas' {frmtab_nat},
  ptab_nat_edi in '..\SHE-OLD\padrao\ptab_nat_edi.pas' {frmtab_nat_edi},
  pven_prg in '..\SHE-OLD\padrao\pven_prg.pas' {frmven_prg},
  pctr_prg in '..\SHE-OLD\padrao\pctr_prg.pas' {frmctr_prg},
  pven_ped in '..\SHE-OLD\padrao\pven_ped.pas' {FrmVEN_PED},
  pctr_ped_bai in '..\SHE-OLD\padrao\pctr_ped_bai.pas' {frmctr_ped_bai},
  pfin_dup_edi in '..\SHE-OLD\padrao\pfin_dup_edi.pas' {frmfin_dup_edi},
  pctr_ped in '..\SHE-OLD\padrao\pctr_ped.pas' {frmctr_ped},
  pcad_con in '..\SHE-OLD\padrao\pcad_con.pas' {frmcad_con},
  pcad_con_edi in '..\SHE-OLD\padrao\pcad_con_edi.pas' {frmcad_con_edi},
  pfin_rec_bai in '..\SHE-OLD\padrao\pfin_rec_bai.pas' {frmfin_rec_bai},
  pfin_rec_con in '..\SHE-OLD\padrao\pfin_rec_con.pas' {frmfin_rec_con},
  pCFeSat in '..\SHE-OLD\padrao\pCFeSat.pas' {FrmCFeSat},
  pcad_for in '..\SHE-OLD\padrao\pcad_for.pas' {frmcad_for},
  pcad_cli_edi in '..\SHE-OLD\padrao\pcad_cli_edi.pas' {frmcad_cli_edi},
  pent_pro in '..\SHE-OLD\Padrao\pent_pro.pas' {frment_pro},
  pven_nfd in '..\SHE-OLD\Padrao\pven_nfd.pas' {frmven_nfd},
  pven_nfe in '..\SHE-OLD\Padrao\pven_nfe.pas' {frmven_nfe},
  peti_pro in '..\SHE-OLD\padrao\peti_pro.pas' {frmeti_pro},
  pSHE_DEF_EDI in '..\SHE-OLD\Padrao\pSHE_DEF_EDI.pas' {FrmSHE_DEF_EDI},
  pCAD_PRO_EDI in '..\SHE-OLD\Padrao\pCAD_PRO_EDI.pas' {FrmCAD_PRO_EDI},
  pcad_cli_inf in '..\SHE-OLD\Padrao\pcad_cli_inf.pas' {frmcad_cli_inf},
  pcai_abr in '..\SHE-OLD\Padrao\pcai_abr.pas' {frmcai_abr},
  pcai_fec in '..\SHE-OLD\Padrao\pcai_fec.pas' {frmcai_fec},
  pcai_mov in '..\SHE-OLD\Padrao\pcai_mov.pas' {frmcai_mov},
  pcai_sar in '..\SHE-OLD\Padrao\pcai_sar.pas' {frmcai_sar},
  pcai_sar_edi in '..\SHE-OLD\Padrao\pcai_sar_edi.pas' {frmcai_sar_edi},
  pEXP_SEP_COL in '..\SHE-OLD\Padrao\pEXP_SEP_COL.pas' {FrmEXP_SEP_COL},
  pEXP_SEP_MAN in '..\SHE-OLD\Padrao\pEXP_SEP_MAN.pas' {FrmEXP_SEP_MAN},
  pimporta_geral in '..\SHE-OLD\Padrao\pimporta_geral.pas' {frmimporta_geral},
  pimporta_geral_favorecido in '..\SHE-OLD\Padrao\pimporta_geral_favorecido.pas' {frmimporta_geral_favorecido},
  pnfe_cce in '..\SHE-OLD\Padrao\pnfe_cce.pas' {frmnfe_cce},
  pNFeConsultaSefaz in '..\SHE-OLD\Padrao\pNFeConsultaSefaz.pas' {FrmNFeConsultaSefaz},
  pemail in '..\SHE-OLD\Padrao\pemail.pas' {FrmEmail},
  pctr_nfe in '..\SHE-OLD\Padrao\pctr_nfe.pas' {frmctr_nfe},
  pEstoque in '..\SHE-OLD\Padrao\pEstoque.pas' {FrmEstoque},
  pCAD_PRO_EST_DEL in '..\SHE-OLD\Padrao\pCAD_PRO_EST_DEL.pas' {FrmCAD_PRO_EST_DEL},
  pven_rom in '..\SHE-OLD\Padrao\pven_rom.pas' {frmven_rom},
  pctr_rom in '..\SHE-OLD\Padrao\pctr_rom.pas' {frmctr_rom},
  pPSQCAD in '..\SHE-OLD\Padrao\pPSQCAD.pas' {FrmPSQCAD},
  pPSQEND in '..\SHE-OLD\Padrao\pPSQEND.pas' {FrmPSQEND},
  pven_prc in '..\SHE-OLD\Padrao\pven_prc.pas' {frmven_prc},
  pctr_prc in '..\SHE-OLD\Padrao\pctr_prc.pas' {frmctr_prc},
  pNFeSaida in '..\SHE-OLD\Padrao\pNFeSaida.pas' {FrmNFeSaida},
  pCAD_TRA in '..\SHE-OLD\Padrao\pCAD_TRA.pas' {FrmCAD_TRA},
  pNFeSaidaConsulta in '..\SHE-OLD\Padrao\pNFeSaidaConsulta.pas' {FrmNFeSaidaConsulta},
  pCAD_REP in '..\SHE-OLD\Padrao\pCAD_REP.pas' {FrmCAD_REP},
  pProduto_Instrucao_Lavagem in '..\SHE-OLD\Padrao\pProduto_Instrucao_Lavagem.pas' {FrmProduto_Instrucao_Lavagem},
  pProduto_Cor in '..\SHE-OLD\Padrao\pProduto_Cor.pas' {FrmProduto_Cor},
  pProduto_Custo_Importado in '..\SHE-OLD\Padrao\pProduto_Custo_Importado.pas' {FrmProduto_Custo_Importado},
  pProduto_Custo_Importado_Edicao in '..\SHE-OLD\Padrao\pProduto_Custo_Importado_Edicao.pas' {FrmProduto_Custo_Importado_Edicao},
  pProduto_Devolucao_Cancelamento in '..\SHE-OLD\Padrao\pProduto_Devolucao_Cancelamento.pas' {FrmProduto_Devolucao_Cancelamento},
  pExporta in '..\SHE-OLD\Padrao\pExporta.pas' {FrmExporta},
  pAviso_Reserva in '..\SHE-OLD\Padrao\pAviso_Reserva.pas' {FrmAviso_Reserva},
  pProduto_Imagem in '..\SHE-OLD\Padrao\pProduto_Imagem.pas' {FrmProduto_Imagem},
  pProduto_SubCategoria in '..\SHE-OLD\Padrao\pProduto_SubCategoria.pas' {FrmProduto_SubCategoria},
  pProduto_Preco_Faixa_Comissao in '..\SHE-OLD\Padrao\pProduto_Preco_Faixa_Comissao.pas' {FrmProduto_Preco_Faixa_Comissao},
  pFRecebimento_Edicao in '..\SHE-OLD\Padrao\pFRecebimento_Edicao.pas' {FrmFRecebimento_Edicao},
  pPesquisaCodigoMunicipal in '..\SHE-OLD\Padrao\pPesquisaCodigoMunicipal.pas' {FrmPesquisaCodigoMunicipal},
  pPesquisaLogradouros in '..\SHE-OLD\Padrao\pPesquisaLogradouros.pas' {FrmPesquisaLogradouros},
  pEstoqueDefeitos in '..\SHE-OLD\Padrao\pEstoqueDefeitos.pas' {FrmEstoqueDefeitos},
  pcad_cli in '..\SHE-OLD\Padrao\pcad_cli.pas' {frmcad_cli},
  pProduto in '..\SHE-OLD\Padrao\pProduto.pas' {FrmProduto},
  prelatorio_geral in '..\SHE-OLD\Relatorios\prelatorio_geral.pas' {frmrelatorio_geral},
  pRelatorios in '..\SHE-OLD\Relatorios\pRelatorios.pas' {FrmRelatorios},
  qPCConferencia in '..\SHE-OLD\Relatorios\qPCConferencia.pas' {qrpPCConferencia: TQuickRep},
  qPCOrdem in '..\SHE-OLD\Relatorios\qPCOrdem.pas' {qrpPCOrdem: TQuickRep},
  qEtiqueta_Cartela in '..\SHE-OLD\Relatorios\qEtiqueta_Cartela.pas' {qrpEtiqueta_Cartela: TQuickRep},
  qEtiqueta_Cartela2 in '..\SHE-OLD\Relatorios\qEtiqueta_Cartela2.pas' {qrpEtiqueta_Cartela2: TQuickRep},
  qEtiqueta_Id in '..\SHE-OLD\Relatorios\qEtiqueta_Id.pas' {qrpEtiqueta_Id: TQuickRep},
  qPROSpedFiscal in '..\SHE-OLD\Relatorios\qPROSpedFiscal.pas' {qrpPROSpedFiscal: TQuickRep},
  qProduto_Custo_Importado in '..\SHE-OLD\Relatorios\qProduto_Custo_Importado.pas' {qrpProduto_Custo_Importado: TQuickRep},
  pProduto_Pesquisa in '..\SHE-OLD\Padrao\pProduto_Pesquisa.pas' {FrmProduto_Pesquisa},
  pProduto_Grupo in '..\SHE-OLD\Padrao\pProduto_Grupo.pas' {FrmProduto_Grupo},
  pProduto_SubGrupo in '..\SHE-OLD\Padrao\pProduto_SubGrupo.pas' {FrmProduto_SubGrupo},
  pProduto_Categoria in '..\SHE-OLD\Padrao\pProduto_Categoria.pas' {FrmProduto_Categoria},
  qProduto_Estoque in '..\SHE-OLD\Relatorios\qProduto_Estoque.pas' {qrpProduto_Estoque: TQuickRep},
  qProduto_Estoque_Etiqueta in '..\SHE-OLD\Relatorios\qProduto_Estoque_Etiqueta.pas' {qrpProduto_Estoque_Etiqueta: TQuickRep},
  qProduto_Compra_Planejamento in '..\SHE-OLD\Relatorios\qProduto_Compra_Planejamento.pas' {qrpProduto_Compra_Planejamento: TQuickRep},
  qGerencial_Estoque_Unidade_Medida in '..\SHE-OLD\Relatorios\qGerencial_Estoque_Unidade_Medida.pas' {qrpGerencial_Estoque_Unidade_Medida: TQuickRep},
  qGerencial_NF_Peso in '..\SHE-OLD\Relatorios\qGerencial_NF_Peso.pas' {qrpGerencial_NF_Peso: TQuickRep},
  qcob_ped_oca in '..\SHE-OLD\Relatorios\qcob_ped_oca.pas' {qrpcob_ped_oca: TQuickRep},
  qcob_rom in '..\SHE-OLD\Relatorios\qcob_rom.pas' {qrpcob_rom: TQuickRep},
  qcob_rom_ref in '..\SHE-OLD\Relatorios\qcob_rom_ref.pas' {qrpcob_rom_ref: TQuickRep},
  qfin_dup in '..\SHE-OLD\Relatorios\qfin_dup.pas' {qrpfin_dup: TQuickRep},
  qfin_rec_ger in '..\SHE-OLD\Relatorios\qfin_rec_ger.pas' {qrpfin_rec_ger: TQuickRep},
  qfin_rec_ger_consolidado in '..\SHE-OLD\Relatorios\qfin_rec_ger_consolidado.pas' {qrpfin_rec_ger_consolidado: TQuickRep},
  qpag_com in '..\SHE-OLD\Relatorios\qpag_com.pas' {qrppag_com: TQuickRep},
  qrom_con_001 in '..\SHE-OLD\Relatorios\qrom_con_001.pas' {qrprom_con_001: TQuickRep},
  qven_prc in '..\SHE-OLD\Relatorios\qven_prc.pas' {qrpven_prc: TQuickRep},
  parquivo_geral in '..\SHE-OLD\padrao\parquivo_geral.pas' {frmarquivo_geral},
  pfin_dup in '..\SHE-OLD\padrao\pfin_dup.pas' {frmfin_dup},
  qven_con in '..\SHE-OLD\Relatorios\qven_con.pas' {qrpven_con: TQuickRep},
  ppag_com in '..\SHE-OLD\padrao\ppag_com.pas' {frmpag_com},
  qven_prg in '..\SHE-OLD\Relatorios\qven_prg.pas' {qrpven_prg: TQuickRep},
  qven_ped in '..\SHE-OLD\Relatorios\qven_ped.pas' {qrpven_ped: TQuickRep},
  qcob_ped in '..\SHE-OLD\Relatorios\qcob_ped.pas' {qrpcob_ped: TQuickRep},
  qsep_ped in '..\SHE-OLD\Relatorios\qsep_ped.pas' {qrpsep_ped: TQuickRep},
  qFicha_Tecnica in '..\SHE-OLD\Relatorios\qFicha_Tecnica.pas' {qrpFicha_Tecnica: TQuickRep},
  qGER_CRD in '..\SHE-OLD\Relatorios\QGER_CRD.pas' {QRPGER_CRD: TQuickRep},
  qEST_ENT_ROM in '..\Lib\Relatórios\Estoque\qEST_ENT_ROM.pas' {qrpEST_ENT_ROM: TQuickRep},
  qEST_ETQ_PAD in '..\Lib\Relatórios\Estoque\qEST_ETQ_PAD.pas' {qrpEST_ETQ_PAD: TQuickRep},
  qEST_ETQ_PEQ in '..\Lib\Relatórios\Estoque\qEST_ETQ_PEQ.pas' {qrpEST_ETQ_PEQ: TQuickRep},
  pNFeConsulta in '..\SHE-OLD\Padrao\pNFeConsulta.pas' {FrmNFeConsulta},
  pProduto_ in '..\SHE-OLD\Padrao\pProduto_.pas' {FrmProduto_};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'SHE ERP';
  FrmSplash := TFrmSplash.Create(Nil);
  FrmSplash.Refresh;
  FrmSplash.Show;

  FBird := TFBird.Create(Application);

  FrmLogin := TFrmLogin.Create(Nil);
  FrmLogin.Refresh;
  FrmLogin.ShowModal;

  Application.CreateForm(TFrmPrincipal, FrmPrincipal);
  Application.Initialize;

  FreeAndNil(FrmSplash);
  FreeAndNil(FrmLogin);

  oExecPrinter(Application.Handle,'Relatórios');
  
  Application.Run;
  FreeAndNil(FrmPrincipal);
end.
